dataset:
  name: mvtec
  format: mvtec
  path: ./datasets/MVTec
  url: ftp://guest:GU.205dldo@ftp.softronics.ch/mvtec_anomaly_detection/mvtec_anomaly_detection.tar.xz
  category: capsule
  task: segmentation
  label_format: None
  image_size: 256
  train_batch_size: 32
  test_batch_size: 32
  inference_batch_size: 16
  num_workers: 36
  training_upsampling: 1000

model:
  name: diffusion
  backbone: wide_resnet50_2
  layers:
    - layer2
    - layer3
    - layer4
  dim_mults: 
    - 1
    - 2
    - 3
    - 4
  lr: 0.0001
  early_stopping:
    patience: 2
    metric: pixel_AUROC
    mode: max
  normalization_method: min_max # options: [null, min_max, cdf]
  threshold:
    image_default: 0
    pixel_default: 0
    adaptive: true
  ema:
    decay: 0.995
    update_steps: 10
    steps_start_ema: 2000

project:
  seed: 0
  path: ./results
  log_images_to: [local, wandb]
  logger: wandb
  save_to_csv: false

# PL Trainer Args. Don't add extra parameter here.
trainer:
  accelerator: gpu
  accumulate_grad_batches: 2
  auto_lr_find: false
  auto_scale_batch_size: false
  auto_select_gpus: false
  benchmark: false
  check_val_every_n_epoch: 1
  checkpoint_callback: true
  default_root_dir: null
  deterministic: false
  fast_dev_run: false
  gpus: 1
  gradient_clip_val: 0
  limit_predict_batches: 1.0
  limit_test_batches: 1.0
  limit_train_batches: 1.0
  limit_val_batches: 1.0
  log_every_n_steps: 50
  log_gpu_memory: null
  max_epochs: -1
  max_steps: 100000
  min_epochs: null
  min_steps: null
  move_metrics_to_cpu: false
  multiple_trainloader_mode: max_size_cycle
  num_nodes: 1
  num_processes: 1
  num_sanity_val_steps: 0
  overfit_batches: 0.0
  plugins: null
  precision: 16
  prepare_data_per_node: true
  process_position: 0
  profiler: null
  progress_bar_refresh_rate: null
  replace_sampler_ddp: true
  stochastic_weight_avg: false
  sync_batchnorm: false
  terminate_on_nan: false
  tpu_cores: null
  track_grad_norm: -1
  val_check_interval: 0.2
  weights_save_path: null
  # resume_from_checkpoint: /home/lucien/repos/anomalib/results/diffusion/mvtec/bottle/weights/model.ckpt
  weights_summary: top
